<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Staff extends MY_Controller
{

 function __construct()
 {
  parent::__construct();
}





function add_staff()
{
  $data['title']="add staff";
  $f_id=$this->session->f_id;
  $params=array('f_id'=>$f_id);
  $get_data=modules::run('api_call/api_call/call_api',''.api_url().'group/groupList',$params,'POST');
  try
  {
    if($get_data=='')
    {
      throw new Exception("server down", 1);
      log_error("group/groupList function error");
      
    }
    if(isset($get_data['error']))
    {
      throw new Exception($get_data['error'], 1);
    }
  }
  catch(Exception $e)
  {
    die(show_error($e->getMessage()));
  }

  if($get_data['status']=='success')
  {

    $data['group']=$get_data['data'];

  }
  $data['_view'] = 'add_staff';
  $this->load->view('index',$data);
}




##add staff process
function add()
{
  $name = htmlspecialchars($this->input->post('name',true));
  $email = $this->input->post('email',true);
  $mobile = $this->input->post('mobile',true);
  $groupId = $this->input->post('group',true);
  $this->load->library('form_validation');
  
  $this->form_validation->set_rules('name','Name','required|trim');
  $this->form_validation->set_rules('email','Email','required|valid_email|trim');

  $this->form_validation->set_rules('mobile','Mobile number','required|exact_length[10]');
 // print_r($this->input->post());die;
  if($this->form_validation->run() )     
  {   

    $f_id=$this->session->f_id;

    $params=array(
      'name'=>$name,
      'email'=>$email,
      'mobile'=>$mobile,
      'created_at'=>date('Y-m-d H:i:s'),
      'f_id'=>$f_id

    );
    // print_r($params);die;
    $get_data=modules::run('api_call/api_call/call_api',''.api_url().'staff/addStaff',$params,'POST');
    if($get_data['status']=='success')
    {
      if(!$groupId[0]=='')
      {
        foreach ($groupId as $row) {
          $mapping=array(
            'group_id'=>$row,
            'member_id'=>$get_data['last_inserted_id']

          );
          $mapInfo = modules::run('api_call/api_call/call_api',''.api_url().'group/addMappingToStaff',$mapping,'POST');
          if($mapInfo['status']=='success')
          {
            $this->session->alerts = array(
              'severity'=> 'success',
              'title'=> 'successfully added'

            );
          }
        }
      }
    #add staff credential
    // modules::run('account/account/autogenerated_username_password',$name,'','',2,$f_id,123,'user_credential',$mobile,$email,$get_data['last_inserted_id']);
    ##autogenerated username and password
    // $short_name='nav';
    
      $password=rand(1,10000).rand(1,9000);
      $encrepted_password=md5($password);
      $username=$f_id.'_'.rand(1,10000);


      $credentialParams=array(
        'username'=>$username,
        'password'=>$encrepted_password,
        'clear_text'=>$password,
        'f_id'=>$f_id,
        'staff_id'=>$get_data['last_inserted_id'],

        'authorization_id'=>2,
        'api_key'=>123
      );


##send username and password in credential table
      $resultPortalLogin=modules::run('api_call/api_call/call_api',''.api_url().'crn/insertUserCredential',$credentialParams,'POST');
    ##send sms to user
      $smsParam=array(
        'mobile'=>$mobile,
        'username'=>$username,
        'password'=>$password,
        'f_id'=>$f_id,
        'module'=>'user credential',
      );
      $sms=modules::run('sms/sms/send_sms_notification',$smsParam,'POST');
     ##send email to frenchise
      $emailParam=array(
        'email'=>$email,
        'username'=>$username,
        'password'=>$password,
        'f_id'=>$f_id,
        'module'=>'user credential',
      );
      $email=modules::run('email/email/send_email_notification',$emailParam,'POST');
      $this->session->alerts = array(
        'severity'=> 'success',
        'title'=> 'successfully added'

      );
      redirect('staff/staff_list');

    }
  // var_dump($get_data);

  }
  else
     {
      $data['_view'] = 'add_staff';
      $this->load->view('index',$data);
    }
  }

  function staff_list()
  {
    $f_id=$this->session->f_id;
    $params=array('f_id'=>$f_id);

    $staff_total = modules::run('api_call/api_call/call_api',''.api_url().'staff/fetchstaff',$params,'POST');
    try
    {
      if($staff_total=='')
      {
        throw new Exception("server down", 1);
        log_error("staff/fetchstaff function error");

      }
      if(isset($staff_total['error']))
      {
        throw new Exception($staff_total['error'], 1);
      }
    }
    catch(Exception $e)
    {
      die(show_error($e->getMessage()));
    }

    if($staff_total['status']=='success')
    {
      $data['staff']=$staff_total['data'];
    }
    else
    {
     $data['staff']=[];
   }
   $data['_view'] = 'staffList';
   $this->load->view('index',$data);


 }
 function edit($id)
 {
  $params=array('id'=>$id);
  $staff_total = modules::run('api_call/api_call/call_api',''.api_url().'staff/fetchstaff',$params,'POST');
  try
  {
    if($staff_total=='')
    {
      throw new Exception("server down", 1);
      log_error("staff/fetchstaff function error");
      
    }
    if(isset($staff_total['error']))
    {
      throw new Exception($staff_total['error'], 1);
    }
  }
  catch(Exception $e)
  {
    die(show_error($e->getMessage()));
  }

  if($staff_total['status']=='success')
  {
    $data['staff']=$staff_total['data'][0];
  }
  // var_dump($staff['data']);
  $data['_view'] = 'edit';
  $this->load->view('index',$data);

}
function update($id)
{
 $name = $this->input->post('name',true);
 $email = $this->input->post('email',true);
 $mobile = $this->input->post('mobile',true);
  // $groupId = $this->input->post('group');
  //  $username = $this->input->post('username');
  // $password = $this->input->post('password');
  // $encrtyted_password=md5($password);

 $f_id=$this->session->f_id;
// if()
 $params=array(
  'id'=>$id,
  'name'=>$name,
  'email'=>$email,
  'mobile'=>$mobile
    // 'created_at'=>date('Y-m-d H:i:s'),
    // 'f_id'=>$f_id

);

 $get_data=modules::run('api_call/api_call/call_api',''.api_url().'staff/updateStaff',$params,'POST');
 try
 {
  if($get_data=='')
  {
    throw new Exception("server down", 1);
    log_error("group/groupList function error");

  }
  if(isset($get_data['error']))
  {
    throw new Exception($get_data['error'], 1);
  }
}
catch(Exception $e)
{
  die(show_error($e->getMessage()));
}


$this->session->alerts = array(
  'severity'=> 'success',
  'title'=> 'updated'

);
redirect('staff/staff_list');

}


function delete_member()
{
  $member_id=$this->input->post('member_id',true);
  $params=array('id'=>$member_id);
  $deleteInfo = modules::run('api_call/api_call/call_api',''.api_url().'staff/remove_member',$params,'POST');
// echo json_encode($deleteInfo);die;
  try
  {
    if($deleteInfo=='')
    {
      throw new Exception("server down", 1);
      log_error("staff/removeMember");

    }
    if(isset($deleteInfo['error']))
    {
      throw new Exception($deleteInfo['error'], 1);
    }
  }
  catch(Exception $e)
  {
    die(show_error($e->getMessage()));
  }
  

  if($deleteInfo['status']=='success')
  {
    echo "success";
  }
 


}




/*all function end*/
}
?>	